
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const NivelPermissao = {
  Administrador: 'Administrador',
  Engenheiro: 'Engenheiro',
  Operador: 'Operador'
} as const

export type NivelPermissao = (typeof NivelPermissao)[keyof typeof NivelPermissao]


export const StatusEtapa = {
  Pendente: 'Pendente',
  Em_Andamento: 'Em_Andamento',
  Concluída: 'Concluída'
} as const

export type StatusEtapa = (typeof StatusEtapa)[keyof typeof StatusEtapa]


export const StatusPeca = {
  Em_Produção: 'Em_Produção',
  Em_Transporte: 'Em_Transporte',
  Pronta: 'Pronta'
} as const

export type StatusPeca = (typeof StatusPeca)[keyof typeof StatusPeca]


export const TipoPeca = {
  Nacional: 'Nacional',
  Importada: 'Importada'
} as const

export type TipoPeca = (typeof TipoPeca)[keyof typeof TipoPeca]


export const TipoTeste = {
  Elétrico: 'Elétrico',
  Hidráulico: 'Hidráulico',
  Aerodinâmico: 'Aerodinâmico'
} as const

export type TipoTeste = (typeof TipoTeste)[keyof typeof TipoTeste]


export const ResultadoTeste = {
  Aprovado: 'Aprovado',
  Reprovado: 'Reprovado'
} as const

export type ResultadoTeste = (typeof ResultadoTeste)[keyof typeof ResultadoTeste]


export const TipoAeronave = {
  Comercial: 'Comercial',
  Militar: 'Militar'
} as const

export type TipoAeronave = (typeof TipoAeronave)[keyof typeof TipoAeronave]
